name: Build and deploy to Docker hub
on:
  push:
    branches: [main]
jobs:
  build_geofence_v1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.6"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          cd geofenceapi_v1
          pip install -r requirements_dev.txt
      - name: Run test suite
        run: |
          cd geofenceapi_v1
          pytest
      - name: Login into docker hub
        env:
          DOCKER_USER: hastman
          DOCKER_PASSWORD: 1cbad0b0-9505-43bb-a363-270f60c50cae
        run: |
          docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
      - name: Build image
        run: |
          cd geofenceapi_v1
          docker build . --tag hastman/scrap_ad_v1:latest
      - name: Push Image
        run: docker push hastman/scrap_ad_v1
